var _hh='';
function hh(p1,p2,t){return [p1.dayGan,p1.dayZhi,p2.dayGan,p2.dayZhi,t].join('|')}
function ih(){var s=localStorage.getItem('hp_rpt');if(!s)return false;try{var d=JSON.parse(s);return d.h===_hh&&d.e>Date.now()}catch(e){return false}}
function sh(){localStorage.setItem('hp_rpt',JSON.stringify({h:_hh,e:Date.now()+7*86400000}))}
function initHePanPaywall(p1,p2,r,t){_hh=hh(p1,p2,t);if(ih()){uh();return}showHPW();autoRestoreHP()}
function showHPW(){var l=document.getElementById('hp-drawer-7');if(!l||document.getElementById('hpw'))return;var c=document.createElement('div');c.id='hpw';c.className='hp-drawer';c.innerHTML='<div class="hp-drawer-header" onclick="document.getElementById('hpw').classList.toggle('hp-open')"><span>📋 完整合盘报告</span><span class="hp-arrow">▶</span></div><div class="hp-drawer-body" style="text-align:center;padding:30px 20px"><p style="color:var(--tx2)">解锁4项深度合盘分析 + 可下载报告</p><div style="font-size:32px;font-weight:900;color:var(--gold-l);margin:12px 0">¥13.9</div><p style="color:var(--tx3);font-size:12px;margin-bottom:20px">一次付费 · 7天有效</p><button class="submit-btn" onclick="shp()" style="max-width:300px">🔓 解锁合盘报告</button><p style="color:var(--tx3);font-size:11px;margin-top:12px">已付费？<a href="javascript:rh()" style="color:var(--gold)">恢复购买</a></p></div>';l.parentNode.insertBefore(c,l.nextSibling)}
function uh(){sh();var c=document.getElementById('hpw');if(c){c.querySelector('.hp-drawer-body').innerHTML='<p style="color:#4f8">✅ 已解锁</p><button class="submit-btn" onclick="if(window.downloadHePanReport)downloadHePanReport()">📥 下载</button>';c.classList.add('hp-open')};['hp-drawer-4','hp-drawer-5','hp-drawer-6','hp-drawer-7'].forEach(function(id){var e=document.getElementById(id);if(e)e.classList.add('hp-open')})}
function shp(){fetch('/api/create-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({money:13.9,name:'合盘完整报告'})}).then(function(r){return r.json()}).then(function(d){if(d.pay_url){localStorage.setItem('hpo',d.out_trade_no);window.open(d.pay_url,'_blank');ph(d.out_trade_no)}else if(d.test_mode){uh()}}).catch(function(){alert('错误')})}
function ph(oid){var n=0;var t=setInterval(function(){n++;if(n>90){clearInterval(t);return};fetch('/api/check-order?out_trade_no='+oid).then(function(r){return r.json()}).then(function(d){if(d.paid){clearInterval(t);localStorage.removeItem('hpo');uh()}}).catch(function(){})},2000)}
function rh(){if(ih()){uh()}else{alert('未找到')}}
function autoRestoreHP(){var oid=localStorage.getItem('hpo');if(oid)ph(oid)}
